def match_slabs(slabs):
    """
    Checks to see if there are any matching slabs generated by SlabGenerator

    Parameters:
        slabs: list of Slab
            A list that contains the slabs generated by SlabGenerator

    Returns:
        bool and tup of int:
            If there are matching slabs in the list, the indices of the matching slabs are returned.
            If no matching slabs, returns False
    """
    matches=[]
    match_identities=[]
    for i in range(len(slabs)):
        for j in range(len(slabs)):
            if i != j:
                val = slabs[i].matches(slabs[j])
                if val:
                    matches.append(slabs[i].matches(slabs[j]))
                    match_identities.append((i, j))
    

    if True in matches:
        return match_identities
    else:
        return False
    

def polar_slabs(slabs):
    """
    Checks to see if any of the slabs generated by SlabGenerated are polar
    
    Parameters:
        slabs: list of Slab
            A list that contains the slabs generated by SlabGenerator

    Returns:
        bool and tup of int:
            If there are polar slabs in the list, the indices of the polar slabs are returned.
            If no polar slabs, returns False
    """
    polar_slabs = []
    for i, slab in enumerate(slabs):
        if slab.is_polar():
            polar_slabs.append(i)

    if polar_slabs != []:
        return polar_slabs
    else:
        return False
    
def symmetric_slabs(slabs):
    """
    Checks to see if any of the slabs generated by SlabGenerated are symmetric
    
    Parameters:
        slabs: list of Slab
            A list that contains the slabs generated by SlabGenerator

    Returns:
        bool and tup of int:
            If there are non-symmetric slabs in the list, the indices of the non-symmetric slabs are returned.
            If all slabs are symmetric, returns False
    """
    non_symmetric_slabs = []
    for i, slab in enumerate(slabs):
        if not slab.is_symmetric():
            non_symmetric_slabs.append(i)

    if non_symmetric_slabs != []:
        return non_symmetric_slabs
    else:
        return False
